name: Python Tests

on:  # [push, pull_request] ???
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '0 5 * * *'
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: set_up_py
      uses: actions/setup-python@v4
      with:
          python-version: '3.x'

    - name: install requirements.txt
       run:
         pip install -r requirements.txt








        
          

    # - name:
    #   uses: 
    #   with:

    # - name:
    #   run: 
